
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Used by Migrate/introspection only — the runtime client connects through
  // the PrismaPg adapter in frontend/src/lib/prisma.ts instead. So this must be
  // DIRECT_URL (session pooler, :5432): DDL over the transaction pooler on
  // :6543 hangs silently rather than erroring.
  datasource: {
    url: env("DIRECT_URL"),
  },
});
